
SP_Gerar_Template_SP_I 'ProdutoMoeda'
SP_Gerar_Template_SP_U 'ProdutoMoeda'
SP_Gerar_Template_SP_G 'ProdutoMoeda'
SP_Gerar_Template_SP_S 'ProdutoMoeda'
SP_Gerar_Template_TR 'ProdutoMoeda'
SP_Gerar_Template_SP_G_Historico 'ProdutoMoeda'
SP_Gerar_Template_SP_S_Historico 'ProdutoMoeda'